AMANDA_FLAGS__=-O3 -Wall -Wmissing-prototypes -Wextra -Wfatal-errors -Werror -I.
FELINE_FLAGS__=-Wno-unused-function
JULIET_FLAGS  =
AMANDA_SIZE   =                              62


amanda_32: bits_32k.o cfft_32k.o common_32k.o decoder_32k.o drc_32k.o drm_dec_32k.o error_32k.o filtbank_32k.o hcr_32k.o huffman_32k.o ic_predict_32k.o is_32k.o lt_predict_32k.o mdct_32k.o mp4_32k.o ms_32k.o output_32k.o pns_32k.o ps_dec_32k.o ps_syntax_32k.o pulse_32k.o rvlc_32k.o sbr_dct_32k.o sbr_dec_32k.o sbr_e_nf_32k.o sbr_fbt_32k.o sbr_hfadj_32k.o            sbr_hfgen_32k.o sbr_huff_32k.o sbr_qmf_32k.o sbr_syntax_32k.o sbr_tf_grid_32k.o specrec_32k.o ssr_32k.o ssr_fb_32k.o ssr_ipqf_32k.o syntax_32k.o tns_32k.o

	i686-w64-mingw32-ar rcs libfaad_32k.a bits_32k.o cfft_32k.o common_32k.o decoder_32k.o drc_32k.o drm_dec_32k.o error_32k.o filtbank_32k.o hcr_32k.o huffman_32k.o ic_predict_32k.o is_32k.o lt_predict_32k.o mdct_32k.o mp4_32k.o ms_32k.o output_32k.o pns_32k.o ps_dec_32k.o ps_syntax_32k.o pulse_32k.o rvlc_32k.o sbr_dct_32k.o sbr_dec_32k.o sbr_e_nf_32k.o 	sbr_fbt_32k.o sbr_hfadj_32k.o sbr_hfgen_32k.o sbr_huff_32k.o sbr_qmf_32k.o sbr_syntax_32k.o sbr_tf_grid_32k.o specrec_32k.o ssr_32k.o ssr_fb_32k.o ssr_ipqf_32k.o syntax_32k.o tns_32k.o

	cp libfaad_32k.a ../
	
bits_32k.o: bits.c
	i686-w64-mingw32-gcc.exe -c -o bits_32k.o bits.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
cfft_32k.o: cfft.c
	i686-w64-mingw32-gcc.exe -c -o cfft_32k.o cfft.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
common_32k.o: common.c
	i686-w64-mingw32-gcc.exe -c -o common_32k.o common.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
decoder_32k.o: decoder.c
	i686-w64-mingw32-gcc.exe -c -o decoder_32k.o decoder.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
drc_32k.o: drc.c
	i686-w64-mingw32-gcc.exe -c -o drc_32k.o drc.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
drm_dec_32k.o: drm_dec.c
	i686-w64-mingw32-gcc.exe -c -o drm_dec_32k.o drm_dec.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
error_32k.o: error.c
	i686-w64-mingw32-gcc.exe -c -o error_32k.o error.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
filtbank_32k.o: filtbank.c
	i686-w64-mingw32-gcc.exe -c -o filtbank_32k.o filtbank.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
hcr_32k.o: hcr.c
	i686-w64-mingw32-gcc.exe -c -o hcr_32k.o hcr.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
huffman_32k.o: huffman.c
	i686-w64-mingw32-gcc.exe -c -o huffman_32k.o huffman.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ic_predict_32k.o: ic_predict.c
	i686-w64-mingw32-gcc.exe -c -o ic_predict_32k.o ic_predict.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
is_32k.o: is.c
	i686-w64-mingw32-gcc.exe -c -o is_32k.o is.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
lt_predict_32k.o: lt_predict.c
	i686-w64-mingw32-gcc.exe -c -o lt_predict_32k.o lt_predict.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
mdct_32k.o: mdct.c
	i686-w64-mingw32-gcc.exe -c -o mdct_32k.o mdct.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
mp4_32k.o: mp4.c
	i686-w64-mingw32-gcc.exe -c -o mp4_32k.o mp4.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ms_32k.o: ms.c
	i686-w64-mingw32-gcc.exe -c -o ms_32k.o ms.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
output_32k.o: output.c
	i686-w64-mingw32-gcc.exe -c -o output_32k.o output.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
pns_32k.o: pns.c
	i686-w64-mingw32-gcc.exe -c -o pns_32k.o pns.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ps_dec_32k.o: ps_dec.c
	i686-w64-mingw32-gcc.exe -c -o ps_dec_32k.o ps_dec.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ps_syntax_32k.o: ps_syntax.c
	i686-w64-mingw32-gcc.exe -c -o ps_syntax_32k.o ps_syntax.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
pulse_32k.o: pulse.c
	i686-w64-mingw32-gcc.exe -c -o pulse_32k.o pulse.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
rvlc_32k.o: rvlc.c
	i686-w64-mingw32-gcc.exe -c -o rvlc_32k.o rvlc.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_dct_32k.o: sbr_dct.c
	i686-w64-mingw32-gcc.exe -c -o sbr_dct_32k.o sbr_dct.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_dec_32k.o: sbr_dec.c
	i686-w64-mingw32-gcc.exe -c -o sbr_dec_32k.o sbr_dec.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_e_nf_32k.o: sbr_e_nf.c
	i686-w64-mingw32-gcc.exe -c -o sbr_e_nf_32k.o sbr_e_nf.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_fbt_32k.o: sbr_fbt.c
	i686-w64-mingw32-gcc.exe -c -o sbr_fbt_32k.o sbr_fbt.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_hfadj_32k.o: sbr_hfadj.c
	i686-w64-mingw32-gcc.exe -c -o sbr_hfadj_32k.o sbr_hfadj.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_hfgen_32k.o: sbr_hfgen.c
	i686-w64-mingw32-gcc.exe -c -o sbr_hfgen_32k.o sbr_hfgen.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_huff_32k.o: sbr_huff.c
	i686-w64-mingw32-gcc.exe -c -o sbr_huff_32k.o sbr_huff.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_qmf_32k.o: sbr_qmf.c
	i686-w64-mingw32-gcc.exe -c -o sbr_qmf_32k.o sbr_qmf.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_syntax_32k.o: sbr_syntax.c
	i686-w64-mingw32-gcc.exe -c -o sbr_syntax_32k.o sbr_syntax.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_tf_grid_32k.o: sbr_tf_grid.c
	i686-w64-mingw32-gcc.exe -c -o sbr_tf_grid_32k.o sbr_tf_grid.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
specrec_32k.o: specrec.c
	i686-w64-mingw32-gcc.exe -c -o specrec_32k.o specrec.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ssr_32k.o: ssr.c
	i686-w64-mingw32-gcc.exe -c -o ssr_32k.o ssr.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ssr_fb_32k.o: ssr_fb.c
	i686-w64-mingw32-gcc.exe -c -o ssr_fb_32k.o ssr_fb.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ssr_ipqf_32k.o: ssr_ipqf.c
	i686-w64-mingw32-gcc.exe -c -o ssr_ipqf_32k.o ssr_ipqf.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
syntax_32k.o: syntax.c
	i686-w64-mingw32-gcc.exe -c -o syntax_32k.o syntax.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z)	$(FELINE_FLAGS__)
	
tns_32k.o: tns.c
	i686-w64-mingw32-gcc.exe -c -o tns_32k.o tns.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ricardo_64: bits_64k.o cfft_64k.o common_64k.o decoder_64k.o drc_64k.o drm_dec_64k.o error_64k.o filtbank_64k.o hcr_64k.o huffman_64k.o ic_predict_64k.o is_64k.o lt_predict_64k.o mdct_64k.o mp4_64k.o ms_64k.o output_64k.o pns_64k.o ps_dec_64k.o ps_syntax_64k.o pulse_64k.o rvlc_64k.o sbr_dct_64k.o sbr_dec_64k.o sbr_e_nf_64k.o sbr_fbt_64k.o sbr_hfadj_64k.o  	sbr_hfgen_64k.o sbr_huff_64k.o sbr_qmf_64k.o sbr_syntax_64k.o sbr_tf_grid_64k.o specrec_64k.o ssr_64k.o ssr_fb_64k.o ssr_ipqf_64k.o syntax_64k.o tns_64k.o

	x86_64-w64-mingw32-ar rcs libfaad_64k.a bits_64k.o cfft_64k.o common_64k.o decoder_64k.o drc_64k.o drm_dec_64k.o error_64k.o filtbank_64k.o hcr_64k.o huffman_64k.o ic_predict_64k.o is_64k.o lt_predict_64k.o mdct_64k.o mp4_64k.o ms_64k.o output_64k.o pns_64k.o ps_dec_64k.o ps_syntax_64k.o pulse_64k.o rvlc_64k.o sbr_dct_64k.o sbr_dec_64k.o sbr_e_nf_64k.o sbr_fbt_64k.o sbr_hfadj_64k.o sbr_hfgen_64k.o sbr_huff_64k.o sbr_qmf_64k.o sbr_syntax_64k.o 	sbr_tf_grid_64k.o specrec_64k.o ssr_64k.o ssr_fb_64k.o ssr_ipqf_64k.o syntax_64k.o tns_64k.o

	cp libfaad_64k.a ../
	
bits_64k.o: bits.c
	x86_64-w64-mingw32-gcc.exe -c -o bits_64k.o bits.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
cfft_64k.o: cfft.c
	x86_64-w64-mingw32-gcc.exe -c -o cfft_64k.o cfft.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
common_64k.o: common.c
	x86_64-w64-mingw32-gcc.exe -c -o common_64k.o common.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
decoder_64k.o: decoder.c
	x86_64-w64-mingw32-gcc.exe -c -o decoder_64k.o decoder.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
drc_64k.o: drc.c
	x86_64-w64-mingw32-gcc.exe -c -o drc_64k.o drc.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
drm_dec_64k.o: drm_dec.c
	x86_64-w64-mingw32-gcc.exe -c -o drm_dec_64k.o drm_dec.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
error_64k.o: error.c
	x86_64-w64-mingw32-gcc.exe -c -o error_64k.o error.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
filtbank_64k.o: filtbank.c
	x86_64-w64-mingw32-gcc.exe -c -o filtbank_64k.o filtbank.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
hcr_64k.o: hcr.c
	x86_64-w64-mingw32-gcc.exe -c -o hcr_64k.o hcr.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)	

huffman_64k.o: huffman.c
	x86_64-w64-mingw32-gcc.exe -c -o huffman_64k.o huffman.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ic_predict_64k.o: ic_predict.c
	x86_64-w64-mingw32-gcc.exe -c -o ic_predict_64k.o ic_predict.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
is_64k.o: is.c
	x86_64-w64-mingw32-gcc.exe -c -o is_64k.o is.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
lt_predict_64k.o: lt_predict.c
	x86_64-w64-mingw32-gcc.exe -c -o lt_predict_64k.o lt_predict.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
mdct_64k.o: mdct.c
	x86_64-w64-mingw32-gcc.exe -c -o mdct_64k.o mdct.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
mp4_64k.o: mp4.c
	x86_64-w64-mingw32-gcc.exe -c -o mp4_64k.o mp4.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ms_64k.o: ms.c
	x86_64-w64-mingw32-gcc.exe -c -o ms_64k.o ms.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
output_64k.o: output.c
	x86_64-w64-mingw32-gcc.exe -c -o output_64k.o output.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
pns_64k.o: pns.c
	x86_64-w64-mingw32-gcc.exe -c -o pns_64k.o pns.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(FELINE_FLAGS__)
	
ps_dec_64k.o: ps_dec.c
	x86_64-w64-mingw32-gcc.exe -c -o ps_dec_64k.o ps_dec.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ps_syntax_64k.o: ps_syntax.c
	x86_64-w64-mingw32-gcc.exe -c -o ps_syntax_64k.o ps_syntax.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
pulse_64k.o: pulse.c
	x86_64-w64-mingw32-gcc.exe -c -o pulse_64k.o pulse.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
rvlc_64k.o: rvlc.c
	x86_64-w64-mingw32-gcc.exe -c -o rvlc_64k.o rvlc.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_dct_64k.o: sbr_dct.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_dct_64k.o sbr_dct.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_dec_64k.o: sbr_dec.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_dec_64k.o sbr_dec.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_e_nf_64k.o: sbr_e_nf.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_e_nf_64k.o sbr_e_nf.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_fbt_64k.o: sbr_fbt.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_fbt_64k.o sbr_fbt.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_hfadj_64k.o: sbr_hfadj.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_hfadj_64k.o sbr_hfadj.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_hfgen_64k.o: sbr_hfgen.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_hfgen_64k.o sbr_hfgen.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_huff_64k.o: sbr_huff.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_huff_64k.o sbr_huff.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_qmf_64k.o: sbr_qmf.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_qmf_64k.o sbr_qmf.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_syntax_64k.o: sbr_syntax.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_syntax_64k.o sbr_syntax.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
sbr_tf_grid_64k.o: sbr_tf_grid.c
	x86_64-w64-mingw32-gcc.exe -c -o sbr_tf_grid_64k.o sbr_tf_grid.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
specrec_64k.o: specrec.c
	x86_64-w64-mingw32-gcc.exe -c -o specrec_64k.o specrec.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ssr_64k.o: ssr.c
	x86_64-w64-mingw32-gcc.exe -c -o ssr_64k.o ssr.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ssr_fb_64k.o: ssr_fb.c
	x86_64-w64-mingw32-gcc.exe -c -o ssr_fb_64k.o ssr_fb.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
ssr_ipqf_64k.o: ssr_ipqf.c
	x86_64-w64-mingw32-gcc.exe -c -o ssr_ipqf_64k.o ssr_ipqf.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
syntax_64k.o: syntax.c
	x86_64-w64-mingw32-gcc.exe -c -o syntax_64k.o syntax.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
tns_64k.o: tns.c
	x86_64-w64-mingw32-gcc.exe -c -o tns_64k.o tns.c $(AMANDA_FLAGS__) $(JULIET_FLAGS) $(Z) $(FELINE_FLAGS__)
	
