
echo para compilar hack_dll 'hack_dll.sh amanda_kp_maria'
echo para unc77.bat em cr_hack.c hack_dll 'hack_dll.sh ricardo'
echo para mp3 dll completo ______________ 'mp3_a_kp.sh'
echo para compilar libav de mp3 _________ 'mp3_libav_a_kp.sh'
echo para compilar mp3 dll clean ________ 'mp3_clean_a_kp.sh'
echo amor, para compilar sdl2 ___________ 'sdl2_kp.sh'
echo amor..., para compilar albatros ____ 'albatros_k.sh'
echo meu amado, para compilar bzip3 _____ 'bzip3_kp.sh'
echo amor para compilar checksum ________ 'rspchecksum_k.sh'
echo amor para compilar rspdb ___________ 'rspdb_k.sh'
echo querido, para compilar encrypt dll _ 'rspencrypt_vilahauer_k.sh'
echo vovo, para compilar rspanyenc ______ 'rspanyenc_k.sh'
echo querido, para compilar rspmfce _____ 'rspmfce_k.sh'
echo amor, para compilar rspmixer _______ 'rspmixer_k.sh'
echo vamos dormar?.............._______  'rspmplayer_k.sh'
echo te amo ....................._____  'tabuleiro_k.sh'
echo vamos dormir? ..........._________  'cosmopolita_k.sh'
echo ta cansado?.............__________ 'derder_k.sh'
echo vamos lá...................______  'parolin_k.sh'
echo para compilar tar-1.32 old ________   'ale_k.sh'
echo para compilar tar-1.32 old ________  'pedro_k.sh e helena_k.sh' tar_1_33 e Luis_rspadv_kp
echo para compilar tar-1.32 new ________  'jair.sh'
echo para compilar rspini impxmlv2 _____  'thalia_arp.sh'
echo para compilar lz4 dll _____________  'cide.sh'
echo para compilar Zstandard ___________  'elisa_arp.sh'

echo ' '
echo if is fast what you want...
