#2021 July 19 - 05:53 - by amanda & ricardo
AMANDA_FLAGS__=-Wall -Wfatal-errors -Werror
APRENDENDO_COM_MEU_MORZAO=/bw_tmp/sdl_2.0/

ricardo_64: $(APRENDENDO_COM_MEU_MORZAO)SDL_atomic.o $(APRENDENDO_COM_MEU_MORZAO)SDL_spinlock.o $(APRENDENDO_COM_MEU_MORZAO)SDL_directsound.o $(APRENDENDO_COM_MEU_MORZAO)SDL_diskaudio.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dummyaudio.o $(APRENDENDO_COM_MEU_MORZAO)SDL_audio.o   \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_audiocvt.o $(APRENDENDO_COM_MEU_MORZAO)SDL_audiodev.o $(APRENDENDO_COM_MEU_MORZAO)SDL_audiotypecvt.o $(APRENDENDO_COM_MEU_MORZAO)SDL_mixer.o $(APRENDENDO_COM_MEU_MORZAO)SDL_wave.o $(APRENDENDO_COM_MEU_MORZAO)SDL_winmm.o             \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_wasapi.o $(APRENDENDO_COM_MEU_MORZAO)SDL_wasapi_win32.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windows.o $(APRENDENDO_COM_MEU_MORZAO)SDL_xinput.o $(APRENDENDO_COM_MEU_MORZAO)SDL_cpuinfo.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dynapi.o           \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_clipboardevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_displayevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dropevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_events.o $(APRENDENDO_COM_MEU_MORZAO)SDL_gesture.o           \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_keyboard.o $(APRENDENDO_COM_MEU_MORZAO)SDL_mouse.o $(APRENDENDO_COM_MEU_MORZAO)SDL_quit.o $(APRENDENDO_COM_MEU_MORZAO)SDL_touch.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_rwops.o                \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_sysfilesystem.o $(APRENDENDO_COM_MEU_MORZAO)SDL_haptic.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dinputhaptic.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowshaptic.o $(APRENDENDO_COM_MEU_MORZAO)SDL_xinputhaptic.o      \
	$(APRENDENDO_COM_MEU_MORZAO)hid.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapijoystick.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_gamecube.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_ps4.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_rumble.o           \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_switch.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xbox360.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xbox360w.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xboxone.o             \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_gamecontroller.o $(APRENDENDO_COM_MEU_MORZAO)SDL_joystick.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dinputjoystick.o $(APRENDENDO_COM_MEU_MORZAO)SDL_mmjoystick.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsjoystick.o \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_xinputjoystick.o $(APRENDENDO_COM_MEU_MORZAO)e_atan2.o $(APRENDENDO_COM_MEU_MORZAO)e_exp.o $(APRENDENDO_COM_MEU_MORZAO)e_fmod.o $(APRENDENDO_COM_MEU_MORZAO)e_log.o $(APRENDENDO_COM_MEU_MORZAO)e_log10.o $(APRENDENDO_COM_MEU_MORZAO)e_pow.o $(APRENDENDO_COM_MEU_MORZAO)e_rem_pio2.o          \
	$(APRENDENDO_COM_MEU_MORZAO)e_sqrt.o $(APRENDENDO_COM_MEU_MORZAO)k_cos.o $(APRENDENDO_COM_MEU_MORZAO)k_rem_pio2.o $(APRENDENDO_COM_MEU_MORZAO)k_sin.o $(APRENDENDO_COM_MEU_MORZAO)kkk_tan.o $(APRENDENDO_COM_MEU_MORZAO)s_atan.o $(APRENDENDO_COM_MEU_MORZAO)s_copysign.o $(APRENDENDO_COM_MEU_MORZAO)s_cos.o $(APRENDENDO_COM_MEU_MORZAO)s_fabs.o          \
	$(APRENDENDO_COM_MEU_MORZAO)s_floor.o $(APRENDENDO_COM_MEU_MORZAO)s_scalbn.o $(APRENDENDO_COM_MEU_MORZAO)s_sin.o $(APRENDENDO_COM_MEU_MORZAO)s_tan.o $(APRENDENDO_COM_MEU_MORZAO)SDL_sysloadso.o $(APRENDENDO_COM_MEU_MORZAO)SDL_power.o $(APRENDENDO_COM_MEU_MORZAO)SDL_syspower.o                 \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_d3d11.o \
	\
	\
	\
	\
	$(APRENDENDO_COM_MEU_MORZAO)SDL_render_d3d.o \
	\
	\
	\
	\
	$(APRENDENDO_COM_MEU_MORZAO)SDL_render_d3d11.o $(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_d3d.o $(APRENDENDO_COM_MEU_MORZAO)SDL_render_gl.o $(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_gl.o \
	\
	\
	\
	\
	\
	$(APRENDENDO_COM_MEU_MORZAO)SDL_render_gles2.o \
	\
	\
	\
	\
	\
	$(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_gles2.o $(APRENDENDO_COM_MEU_MORZAO)SDL_d3dmath.o $(APRENDENDO_COM_MEU_MORZAO)SDL_render.o $(APRENDENDO_COM_MEU_MORZAO)SDL_yuv_sw.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blendfillrect.o                 \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_blendline.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blendpoint.o  $(APRENDENDO_COM_MEU_MORZAO)SDL_drawline.o $(APRENDENDO_COM_MEU_MORZAO)SDL_drawpoint.o $(APRENDENDO_COM_MEU_MORZAO)SDL_render_sw.o $(APRENDENDO_COM_MEU_MORZAO)SDL_rotate.o   \
	$(APRENDENDO_COM_MEU_MORZAO)SDL.o $(APRENDENDO_COM_MEU_MORZAO)SDL_assert.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dataqueue.o $(APRENDENDO_COM_MEU_MORZAO)SDL_error.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hints.o $(APRENDENDO_COM_MEU_MORZAO)SDL_log.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dummysensor.o          \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_sensor.o $(APRENDENDO_COM_MEU_MORZAO)SDL_getenv.o $(APRENDENDO_COM_MEU_MORZAO)SDL_iconv.o $(APRENDENDO_COM_MEU_MORZAO)SDL_kkkkk_malloc.o $(APRENDENDO_COM_MEU_MORZAO)SDL_qsort.o $(APRENDENDO_COM_MEU_MORZAO)SDL_stdlib.o $(APRENDENDO_COM_MEU_MORZAO)SDL_string.o  \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_strtokr.o $(APRENDENDO_COM_MEU_MORZAO)SDL_syscond.o $(APRENDENDO_COM_MEU_MORZAO)SDL_thread.o $(APRENDENDO_COM_MEU_MORZAO)SDL_sysmutex.o $(APRENDENDO_COM_MEU_MORZAO)SDL_syssem.o $(APRENDENDO_COM_MEU_MORZAO)SDL_systhread.o            \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_systls.o $(APRENDENDO_COM_MEU_MORZAO)SDL_timer.o $(APRENDENDO_COM_MEU_MORZAO)SDL_systimer.o $(APRENDENDO_COM_MEU_MORZAO)SDL_nullevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_nullframebuffer.o $(APRENDENDO_COM_MEU_MORZAO)SDL_nullvideo.o  \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_blit.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_0.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_1.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_A.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_auto.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_copy.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_N.o  \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_blit_slow.o $(APRENDENDO_COM_MEU_MORZAO)SDL_bmp.o $(APRENDENDO_COM_MEU_MORZAO)SDL_clipboard.o $(APRENDENDO_COM_MEU_MORZAO)SDL_egl.o $(APRENDENDO_COM_MEU_MORZAO)SDL_fillrect.o $(APRENDENDO_COM_MEU_MORZAO)SDL_pixels.o $(APRENDENDO_COM_MEU_MORZAO)SDL_rect.o      \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_RLEaccel.o $(APRENDENDO_COM_MEU_MORZAO)SDL_shape.o $(APRENDENDO_COM_MEU_MORZAO)SDL_stretch.o $(APRENDENDO_COM_MEU_MORZAO)SDL_surface.o $(APRENDENDO_COM_MEU_MORZAO)SDL_video.o $(APRENDENDO_COM_MEU_MORZAO)SDL_vulkan_utils.o           \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_yuv.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsclipboard.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsframebuffer.o                   \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_windowskeyboard.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmessagebox.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmodes.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmouse.o             \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsopengl.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsopengles.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsshape.o   $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsvideo.o             \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsvulkan.o   $(APRENDENDO_COM_MEU_MORZAO)SDL_windowswindow.o   $(APRENDENDO_COM_MEU_MORZAO)yuv_rgb.o $(APRENDENDO_COM_MEU_MORZAO)dprintf_kp.o

	/bw_tmp/amandaricardo_mvbuild26_33.exe ./amanda_file_counter_32.ini versio_n.ama.rc version_ricardo_mislaine_final_2_.rc aline_definitive_header_2_.h "64 bits" mod_sdl2_2_0_12_kp.dll increase

	x86_64-w64-mingw32-windres -O coff -o $(APRENDENDO_COM_MEU_MORZAO)version64.o version_ricardo_mislaine_final_2_.rc

	x86_64-w64-mingw32-gcc.exe -mdll -o $(APRENDENDO_COM_MEU_MORZAO)mod_sdl2_2_0_12_kp.dll $(APRENDENDO_COM_MEU_MORZAO)SDL_atomic.o $(APRENDENDO_COM_MEU_MORZAO)SDL_spinlock.o          \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_directsound.o $(APRENDENDO_COM_MEU_MORZAO)SDL_diskaudio.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dummyaudio.o $(APRENDENDO_COM_MEU_MORZAO)SDL_audio.o                                  \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_audiocvt.o $(APRENDENDO_COM_MEU_MORZAO)SDL_audiodev.o $(APRENDENDO_COM_MEU_MORZAO)SDL_audiotypecvt.o $(APRENDENDO_COM_MEU_MORZAO)SDL_mixer.o $(APRENDENDO_COM_MEU_MORZAO)SDL_wave.o $(APRENDENDO_COM_MEU_MORZAO)SDL_winmm.o             \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_wasapi.o $(APRENDENDO_COM_MEU_MORZAO)SDL_wasapi_win32.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windows.o $(APRENDENDO_COM_MEU_MORZAO)SDL_xinput.o $(APRENDENDO_COM_MEU_MORZAO)SDL_cpuinfo.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dynapi.o           \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_clipboardevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_displayevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dropevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_events.o $(APRENDENDO_COM_MEU_MORZAO)SDL_gesture.o           \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_keyboard.o $(APRENDENDO_COM_MEU_MORZAO)SDL_mouse.o $(APRENDENDO_COM_MEU_MORZAO)SDL_quit.o $(APRENDENDO_COM_MEU_MORZAO)SDL_touch.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_rwops.o                \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_sysfilesystem.o $(APRENDENDO_COM_MEU_MORZAO)SDL_haptic.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dinputhaptic.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowshaptic.o $(APRENDENDO_COM_MEU_MORZAO)SDL_xinputhaptic.o      \
	$(APRENDENDO_COM_MEU_MORZAO)hid.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapijoystick.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_gamecube.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_ps4.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_rumble.o           \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_switch.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xbox360.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xbox360w.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xboxone.o             \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_gamecontroller.o $(APRENDENDO_COM_MEU_MORZAO)SDL_joystick.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dinputjoystick.o $(APRENDENDO_COM_MEU_MORZAO)SDL_mmjoystick.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsjoystick.o \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_xinputjoystick.o $(APRENDENDO_COM_MEU_MORZAO)e_atan2.o $(APRENDENDO_COM_MEU_MORZAO)e_exp.o $(APRENDENDO_COM_MEU_MORZAO)e_fmod.o $(APRENDENDO_COM_MEU_MORZAO)e_log.o $(APRENDENDO_COM_MEU_MORZAO)e_log10.o $(APRENDENDO_COM_MEU_MORZAO)e_pow.o $(APRENDENDO_COM_MEU_MORZAO)e_rem_pio2.o          \
	$(APRENDENDO_COM_MEU_MORZAO)e_sqrt.o $(APRENDENDO_COM_MEU_MORZAO)k_cos.o $(APRENDENDO_COM_MEU_MORZAO)k_rem_pio2.o $(APRENDENDO_COM_MEU_MORZAO)k_sin.o $(APRENDENDO_COM_MEU_MORZAO)kkk_tan.o $(APRENDENDO_COM_MEU_MORZAO)s_atan.o $(APRENDENDO_COM_MEU_MORZAO)s_copysign.o $(APRENDENDO_COM_MEU_MORZAO)s_cos.o $(APRENDENDO_COM_MEU_MORZAO)s_fabs.o          \
	$(APRENDENDO_COM_MEU_MORZAO)s_floor.o $(APRENDENDO_COM_MEU_MORZAO)s_scalbn.o $(APRENDENDO_COM_MEU_MORZAO)s_sin.o $(APRENDENDO_COM_MEU_MORZAO)s_tan.o $(APRENDENDO_COM_MEU_MORZAO)SDL_sysloadso.o $(APRENDENDO_COM_MEU_MORZAO)SDL_power.o $(APRENDENDO_COM_MEU_MORZAO)SDL_syspower.o                 \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_d3d11.o \
	\
	\
	\
	\
	$(APRENDENDO_COM_MEU_MORZAO)SDL_render_d3d.o \
	\
	\
	\
	\
	$(APRENDENDO_COM_MEU_MORZAO)SDL_render_d3d11.o $(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_d3d.o $(APRENDENDO_COM_MEU_MORZAO)SDL_render_gl.o $(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_gl.o \
	\
	\
	\
	\
	\
	$(APRENDENDO_COM_MEU_MORZAO)SDL_render_gles2.o \
	\
	\
	\
	\
	\
	$(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_gles2.o $(APRENDENDO_COM_MEU_MORZAO)SDL_d3dmath.o $(APRENDENDO_COM_MEU_MORZAO)SDL_render.o $(APRENDENDO_COM_MEU_MORZAO)SDL_yuv_sw.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blendfillrect.o                 \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_blendline.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blendpoint.o  $(APRENDENDO_COM_MEU_MORZAO)SDL_drawline.o $(APRENDENDO_COM_MEU_MORZAO)SDL_drawpoint.o $(APRENDENDO_COM_MEU_MORZAO)SDL_render_sw.o $(APRENDENDO_COM_MEU_MORZAO)SDL_rotate.o   \
	$(APRENDENDO_COM_MEU_MORZAO)SDL.o $(APRENDENDO_COM_MEU_MORZAO)SDL_assert.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dataqueue.o $(APRENDENDO_COM_MEU_MORZAO)SDL_error.o $(APRENDENDO_COM_MEU_MORZAO)SDL_hints.o $(APRENDENDO_COM_MEU_MORZAO)SDL_log.o $(APRENDENDO_COM_MEU_MORZAO)SDL_dummysensor.o          \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_sensor.o $(APRENDENDO_COM_MEU_MORZAO)SDL_getenv.o $(APRENDENDO_COM_MEU_MORZAO)SDL_iconv.o $(APRENDENDO_COM_MEU_MORZAO)SDL_kkkkk_malloc.o $(APRENDENDO_COM_MEU_MORZAO)SDL_qsort.o $(APRENDENDO_COM_MEU_MORZAO)SDL_stdlib.o $(APRENDENDO_COM_MEU_MORZAO)SDL_string.o  \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_strtokr.o $(APRENDENDO_COM_MEU_MORZAO)SDL_syscond.o $(APRENDENDO_COM_MEU_MORZAO)SDL_thread.o $(APRENDENDO_COM_MEU_MORZAO)SDL_sysmutex.o $(APRENDENDO_COM_MEU_MORZAO)SDL_syssem.o $(APRENDENDO_COM_MEU_MORZAO)SDL_systhread.o            \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_systls.o $(APRENDENDO_COM_MEU_MORZAO)SDL_timer.o $(APRENDENDO_COM_MEU_MORZAO)SDL_systimer.o $(APRENDENDO_COM_MEU_MORZAO)SDL_nullevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_nullframebuffer.o $(APRENDENDO_COM_MEU_MORZAO)SDL_nullvideo.o  \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_blit.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_0.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_1.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_A.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_auto.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_copy.o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_N.o  \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_blit_slow.o $(APRENDENDO_COM_MEU_MORZAO)SDL_bmp.o $(APRENDENDO_COM_MEU_MORZAO)SDL_clipboard.o $(APRENDENDO_COM_MEU_MORZAO)SDL_egl.o $(APRENDENDO_COM_MEU_MORZAO)SDL_fillrect.o $(APRENDENDO_COM_MEU_MORZAO)SDL_pixels.o $(APRENDENDO_COM_MEU_MORZAO)SDL_rect.o      \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_RLEaccel.o $(APRENDENDO_COM_MEU_MORZAO)SDL_shape.o $(APRENDENDO_COM_MEU_MORZAO)SDL_stretch.o $(APRENDENDO_COM_MEU_MORZAO)SDL_surface.o $(APRENDENDO_COM_MEU_MORZAO)SDL_video.o $(APRENDENDO_COM_MEU_MORZAO)SDL_vulkan_utils.o           \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_yuv.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsclipboard.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsevents.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsframebuffer.o                   \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_windowskeyboard.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmessagebox.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmodes.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmouse.o             \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsopengl.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsopengles.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsshape.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsvideo.o             \
	$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsvulkan.o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowswindow.o $(APRENDENDO_COM_MEU_MORZAO)yuv_rgb.o $(APRENDENDO_COM_MEU_MORZAO)version64.o $(APRENDENDO_COM_MEU_MORZAO)dprintf_kp.o -ldxguid        \
	-ldinput -lddraw -lwinmm -lGdi32 -lole32 -lsetupapi -lhid -limm32 -lversion -loleaut32 amanda.def

	(cd /bw_tmp/sdl_2.0/ && cp --preserve=timestamps *.dll /bin/mp3dll)

#unc77.bat ../../src/video/SDL_video.c
#unc77.bat ../../src/video/windows/SDL_windowswindow.c
$(APRENDENDO_COM_MEU_MORZAO)dprintf_kp.o: dprintf_kp.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) dprintf_kp.c -o $(APRENDENDO_COM_MEU_MORZAO)dprintf_kp.o
$(APRENDENDO_COM_MEU_MORZAO)SDL_atomic.o: ../../src/atomic/SDL_atomic.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/atomic/SDL_atomic.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_atomic.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_spinlock.o: ../../src/atomic/SDL_spinlock.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/atomic/SDL_spinlock.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_spinlock.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_directsound.o: ../../src/audio/directsound/SDL_directsound.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/directsound/SDL_directsound.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_directsound.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_diskaudio.o: ../../src/audio/disk/SDL_diskaudio.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/disk/SDL_diskaudio.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_diskaudio.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_dummyaudio.o: ../../src/audio/dummy/SDL_dummyaudio.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/dummy/SDL_dummyaudio.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_dummyaudio.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_audio.o: ../../src/audio/SDL_audio.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/SDL_audio.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_audio.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_audiocvt.o: ../../src/audio/SDL_audiocvt.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/SDL_audiocvt.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_audiocvt.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_audiodev.o: ../../src/audio/SDL_audiodev.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/SDL_audiodev.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_audiodev.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_audiotypecvt.o: ../../src/audio/SDL_audiotypecvt.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/SDL_audiotypecvt.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_audiotypecvt.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_mixer.o: ../../src/audio/SDL_mixer.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/SDL_mixer.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_mixer.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_wave.o: ../../src/audio/SDL_wave.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/SDL_wave.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_wave.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_winmm.o: ../../src/audio/winmm/SDL_winmm.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/winmm/SDL_winmm.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_winmm.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_wasapi.o: ../../src/audio/wasapi/SDL_wasapi.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/wasapi/SDL_wasapi.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_wasapi.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_wasapi_win32.o: ../../src/audio/wasapi/SDL_wasapi_win32.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/audio/wasapi/SDL_wasapi_win32.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_wasapi_win32.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windows.o: ../../src/core/windows/SDL_windows.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/core/windows/SDL_windows.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windows.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_xinput.o: ../../src/core/windows/SDL_xinput.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/core/windows/SDL_xinput.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_xinput.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_cpuinfo.o: ../../src/cpuinfo/SDL_cpuinfo.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/cpuinfo/SDL_cpuinfo.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_cpuinfo.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_dynapi.o: ../../src/dynapi/SDL_dynapi.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/dynapi/SDL_dynapi.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_dynapi.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_clipboardevents.o: ../../src/events/SDL_clipboardevents.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_clipboardevents.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_clipboardevents.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_displayevents.o: ../../src/events/SDL_displayevents.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_displayevents.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_displayevents.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_dropevents.o: ../../src/events/SDL_dropevents.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_dropevents.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_dropevents.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_events.o: ../../src/events/SDL_events.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_events.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_events.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_gesture.o: ../../src/events/SDL_gesture.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_gesture.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_gesture.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_keyboard.o: ../../src/events/SDL_keyboard.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_keyboard.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_keyboard.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_mouse.o: ../../src/events/SDL_mouse.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_mouse.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_mouse.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_quit.o: ../../src/events/SDL_quit.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_quit.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_quit.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_touch.o: ../../src/events/SDL_touch.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_touch.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_touch.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowevents.o: ../../src/events/SDL_windowevents.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/events/SDL_windowevents.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowevents.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_rwops.o: ../../src/file/SDL_rwops.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/file/SDL_rwops.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_rwops.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_sysfilesystem.o: ../../src/filesystem/windows/SDL_sysfilesystem.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/filesystem/windows/SDL_sysfilesystem.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_sysfilesystem.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_haptic.o: ../../src/haptic/SDL_haptic.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/haptic/SDL_haptic.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_haptic.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_dinputhaptic.o: ../../src/haptic/windows/SDL_dinputhaptic.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/haptic/windows/SDL_dinputhaptic.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_dinputhaptic.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowshaptic.o: ../../src/haptic/windows/SDL_windowshaptic.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/haptic/windows/SDL_windowshaptic.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowshaptic.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_xinputhaptic.o: ../../src/haptic/windows/SDL_xinputhaptic.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/haptic/windows/SDL_xinputhaptic.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_xinputhaptic.o

$(APRENDENDO_COM_MEU_MORZAO)hid.o: ../../src/hidapi/windows/hid.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/hidapi/windows/hid.c" -o $(APRENDENDO_COM_MEU_MORZAO)hid.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapijoystick.o: ../../src/joystick/hidapi/SDL_hidapijoystick.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/hidapi/SDL_hidapijoystick.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapijoystick.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_gamecube.o: ../../src/joystick/hidapi/SDL_hidapi_gamecube.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/hidapi/SDL_hidapi_gamecube.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_gamecube.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_ps4.o: ../../src/joystick/hidapi/SDL_hidapi_ps4.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/hidapi/SDL_hidapi_ps4.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_ps4.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_rumble.o: ../../src/joystick/hidapi/SDL_hidapi_rumble.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/hidapi/SDL_hidapi_rumble.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_rumble.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_switch.o: ../../src/joystick/hidapi/SDL_hidapi_switch.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/hidapi/SDL_hidapi_switch.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_switch.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xbox360.o: ../../src/joystick/hidapi/SDL_hidapi_xbox360.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/hidapi/SDL_hidapi_xbox360.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xbox360.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xbox360w.o: ../../src/joystick/hidapi/SDL_hidapi_xbox360w.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/hidapi/SDL_hidapi_xbox360w.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xbox360w.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xboxone.o: ../../src/joystick/hidapi/SDL_hidapi_xboxone.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/hidapi/SDL_hidapi_xboxone.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_hidapi_xboxone.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_gamecontroller.o: ../../src/joystick/SDL_gamecontroller.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/SDL_gamecontroller.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_gamecontroller.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_joystick.o: ../../src/joystick/SDL_joystick.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/SDL_joystick.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_joystick.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_dinputjoystick.o: ../../src/joystick/windows/SDL_dinputjoystick.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/windows/SDL_dinputjoystick.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_dinputjoystick.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_mmjoystick.o: ../../src/joystick/windows/SDL_mmjoystick.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/windows/SDL_mmjoystick.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_mmjoystick.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsjoystick.o: ../../src/joystick/windows/SDL_windowsjoystick.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/windows/SDL_windowsjoystick.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsjoystick.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_xinputjoystick.o: ../../src/joystick/windows/SDL_xinputjoystick.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/joystick/windows/SDL_xinputjoystick.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_xinputjoystick.o

$(APRENDENDO_COM_MEU_MORZAO)e_atan2.o: ../../src/libm/e_atan2.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/e_atan2.c" -o $(APRENDENDO_COM_MEU_MORZAO)e_atan2.o

$(APRENDENDO_COM_MEU_MORZAO)e_exp.o: ../../src/libm/e_exp.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/e_exp.c" -o $(APRENDENDO_COM_MEU_MORZAO)e_exp.o

$(APRENDENDO_COM_MEU_MORZAO)e_fmod.o: ../../src/libm/e_fmod.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/e_fmod.c" -o $(APRENDENDO_COM_MEU_MORZAO)e_fmod.o

$(APRENDENDO_COM_MEU_MORZAO)e_log.o: ../../src/libm/e_log.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/e_log.c" -o $(APRENDENDO_COM_MEU_MORZAO)e_log.o

$(APRENDENDO_COM_MEU_MORZAO)e_log10.o: ../../src/libm/e_log10.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/e_log10.c" -o $(APRENDENDO_COM_MEU_MORZAO)e_log10.o

$(APRENDENDO_COM_MEU_MORZAO)e_pow.o: ../../src/libm/e_pow.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/e_pow.c" -o $(APRENDENDO_COM_MEU_MORZAO)e_pow.o

$(APRENDENDO_COM_MEU_MORZAO)e_rem_pio2.o: ../../src/libm/e_rem_pio2.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/e_rem_pio2.c" -o $(APRENDENDO_COM_MEU_MORZAO)e_rem_pio2.o

$(APRENDENDO_COM_MEU_MORZAO)e_sqrt.o: ../../src/libm/e_sqrt.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/e_sqrt.c" -o $(APRENDENDO_COM_MEU_MORZAO)e_sqrt.o

$(APRENDENDO_COM_MEU_MORZAO)k_cos.o: ../../src/libm/k_cos.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/k_cos.c" -o $(APRENDENDO_COM_MEU_MORZAO)k_cos.o

$(APRENDENDO_COM_MEU_MORZAO)k_rem_pio2.o: ../../src/libm/k_rem_pio2.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/k_rem_pio2.c" -o $(APRENDENDO_COM_MEU_MORZAO)k_rem_pio2.o

$(APRENDENDO_COM_MEU_MORZAO)k_sin.o: ../../src/libm/k_sin.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/k_sin.c" -o $(APRENDENDO_COM_MEU_MORZAO)k_sin.o

$(APRENDENDO_COM_MEU_MORZAO)kkk_tan.o: ../../src/libm/k_tan.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/k_tan.c" -o $(APRENDENDO_COM_MEU_MORZAO)kkk_tan.o

$(APRENDENDO_COM_MEU_MORZAO)s_atan.o: ../../src/libm/s_atan.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/s_atan.c" -o $(APRENDENDO_COM_MEU_MORZAO)s_atan.o

$(APRENDENDO_COM_MEU_MORZAO)s_copysign.o: ../../src/libm/s_copysign.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/s_copysign.c" -o $(APRENDENDO_COM_MEU_MORZAO)s_copysign.o

$(APRENDENDO_COM_MEU_MORZAO)s_cos.o: ../../src/libm/s_cos.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/s_cos.c" -o $(APRENDENDO_COM_MEU_MORZAO)s_cos.o

$(APRENDENDO_COM_MEU_MORZAO)s_fabs.o: ../../src/libm/s_fabs.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/s_fabs.c" -o $(APRENDENDO_COM_MEU_MORZAO)s_fabs.o

$(APRENDENDO_COM_MEU_MORZAO)s_floor.o: ../../src/libm/s_floor.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/s_floor.c" -o $(APRENDENDO_COM_MEU_MORZAO)s_floor.o

$(APRENDENDO_COM_MEU_MORZAO)s_scalbn.o: ../../src/libm/s_scalbn.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/s_scalbn.c" -o $(APRENDENDO_COM_MEU_MORZAO)s_scalbn.o

$(APRENDENDO_COM_MEU_MORZAO)s_sin.o: ../../src/libm/s_sin.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/s_sin.c" -o $(APRENDENDO_COM_MEU_MORZAO)s_sin.o

$(APRENDENDO_COM_MEU_MORZAO)s_tan.o: ../../src/libm/s_tan.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/libm/s_tan.c" -o $(APRENDENDO_COM_MEU_MORZAO)s_tan.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_sysloadso.o: ../../src/loadso/windows/SDL_sysloadso.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/loadso/windows/SDL_sysloadso.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_sysloadso.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_power.o: ../../src/power/SDL_power.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/power/SDL_power.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_power.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_syspower.o: ../../src/power/windows/SDL_syspower.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/power/windows/SDL_syspower.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_syspower.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_d3d11.o: ../../src/render/direct3d11/SDL_shaders_d3d11.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/direct3d11/SDL_shaders_d3d11.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_d3d11.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_render_d3d.o: ../../src/render/direct3d/SDL_render_d3d.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/direct3d/SDL_render_d3d.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_render_d3d.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_render_d3d11.o: ../../src/render/direct3d11/SDL_render_d3d11.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/direct3d11/SDL_render_d3d11.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_render_d3d11.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_d3d.o: ../../src/render/direct3d/SDL_shaders_d3d.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/direct3d/SDL_shaders_d3d.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_d3d.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_render_gl.o: ../../src/render/opengl/SDL_render_gl.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/opengl/SDL_render_gl.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_render_gl.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_gl.o: ../../src/render/opengl/SDL_shaders_gl.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/opengl/SDL_shaders_gl.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_gl.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_render_gles2.o: ../../src/render/opengles2/SDL_render_gles2.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/opengles2/SDL_render_gles2.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_render_gles2.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_gles2.o: ../../src/render/opengles2/SDL_shaders_gles2.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/opengles2/SDL_shaders_gles2.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_shaders_gles2.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_d3dmath.o: ../../src/render/SDL_d3dmath.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/SDL_d3dmath.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_d3dmath.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_render.o: ../../src/render/SDL_render.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/SDL_render.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_render.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_yuv_sw.o: ../../src/render/SDL_yuv_sw.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/SDL_yuv_sw.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_yuv_sw.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blendfillrect.o: ../../src/render/software/SDL_blendfillrect.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/software/SDL_blendfillrect.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blendfillrect.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blendline.o: ../../src/render/software/SDL_blendline.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/software/SDL_blendline.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blendline.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blendpoint.o: ../../src/render/software/SDL_blendpoint.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/software/SDL_blendpoint.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blendpoint.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_drawline.o: ../../src/render/software/SDL_drawline.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/software/SDL_drawline.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_drawline.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_drawpoint.o: ../../src/render/software/SDL_drawpoint.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/software/SDL_drawpoint.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_drawpoint.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_render_sw.o: ../../src/render/software/SDL_render_sw.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/software/SDL_render_sw.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_render_sw.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_rotate.o: ../../src/render/software/SDL_rotate.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/render/software/SDL_rotate.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_rotate.o

$(APRENDENDO_COM_MEU_MORZAO)SDL.o: ../../src/SDL.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/SDL.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_assert.o: ../../src/SDL_assert.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/SDL_assert.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_assert.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_dataqueue.o: ../../src/SDL_dataqueue.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/SDL_dataqueue.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_dataqueue.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_error.o: ../../src/SDL_error.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/SDL_error.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_error.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_hints.o: ../../src/SDL_hints.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/SDL_hints.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_hints.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_log.o: ../../src/SDL_log.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/SDL_log.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_log.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_dummysensor.o: ../../src/sensor/dummy/SDL_dummysensor.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/sensor/dummy/SDL_dummysensor.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_dummysensor.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_sensor.o: ../../src/sensor/SDL_sensor.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/sensor/SDL_sensor.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_sensor.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_getenv.o: ../../src/stdlib/SDL_getenv.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/stdlib/SDL_getenv.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_getenv.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_iconv.o: ../../src/stdlib/SDL_iconv.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/stdlib/SDL_iconv.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_iconv.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_kkkkk_malloc.o: ../../src/stdlib/SDL_malloc.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/stdlib/SDL_malloc.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_kkkkk_malloc.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_qsort.o: ../../src/stdlib/SDL_qsort.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/stdlib/SDL_qsort.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_qsort.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_stdlib.o: ../../src/stdlib/SDL_stdlib.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/stdlib/SDL_stdlib.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_stdlib.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_string.o: ../../src/stdlib/SDL_string.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/stdlib/SDL_string.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_string.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_strtokr.o: ../../src/stdlib/SDL_strtokr.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/stdlib/SDL_strtokr.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_strtokr.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_syscond.o: ../../src/thread/generic/SDL_syscond.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/thread/generic/SDL_syscond.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_syscond.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_thread.o: ../../src/thread/SDL_thread.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/thread/SDL_thread.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_thread.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_sysmutex.o: ../../src/thread/windows/SDL_sysmutex.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/thread/windows/SDL_sysmutex.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_sysmutex.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_syssem.o: ../../src/thread/windows/SDL_syssem.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/thread/windows/SDL_syssem.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_syssem.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_systhread.o: ../../src/thread/windows/SDL_systhread.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/thread/windows/SDL_systhread.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_systhread.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_systls.o: ../../src/thread/windows/SDL_systls.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/thread/windows/SDL_systls.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_systls.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_timer.o: ../../src/timer/SDL_timer.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/timer/SDL_timer.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_timer.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_systimer.o: ../../src/timer/windows/SDL_systimer.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/timer/windows/SDL_systimer.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_systimer.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_nullevents.o: ../../src/video/dummy/SDL_nullevents.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/dummy/SDL_nullevents.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_nullevents.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_nullframebuffer.o: ../../src/video/dummy/SDL_nullframebuffer.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/dummy/SDL_nullframebuffer.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_nullframebuffer.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_nullvideo.o: ../../src/video/dummy/SDL_nullvideo.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/dummy/SDL_nullvideo.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_nullvideo.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blit.o: ../../src/video/SDL_blit.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_blit.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blit_0.o: ../../src/video/SDL_blit_0.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_blit_0.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_0.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blit_1.o: ../../src/video/SDL_blit_1.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_blit_1.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_1.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blit_A.o: ../../src/video/SDL_blit_A.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_blit_A.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_A.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blit_auto.o: ../../src/video/SDL_blit_auto.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_blit_auto.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_auto.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blit_copy.o: ../../src/video/SDL_blit_copy.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_blit_copy.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_copy.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blit_N.o: ../../src/video/SDL_blit_N.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_blit_N.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_N.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_blit_slow.o: ../../src/video/SDL_blit_slow.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_blit_slow.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_blit_slow.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_bmp.o: ../../src/video/SDL_bmp.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_bmp.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_bmp.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_clipboard.o: ../../src/video/SDL_clipboard.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_clipboard.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_clipboard.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_egl.o: ../../src/video/SDL_egl.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_egl.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_egl.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_fillrect.o: ../../src/video/SDL_fillrect.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_fillrect.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_fillrect.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_pixels.o: ../../src/video/SDL_pixels.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_pixels.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_pixels.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_rect.o: ../../src/video/SDL_rect.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_rect.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_rect.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_RLEaccel.o: ../../src/video/SDL_RLEaccel.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_RLEaccel.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_RLEaccel.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_shape.o: ../../src/video/SDL_shape.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_shape.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_shape.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_stretch.o: ../../src/video/SDL_stretch.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_stretch.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_stretch.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_surface.o: ../../src/video/SDL_surface.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_surface.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_surface.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_video.o: ../../src/video/SDL_video.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_video.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_video.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_vulkan_utils.o: ../../src/video/SDL_vulkan_utils.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_vulkan_utils.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_vulkan_utils.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_yuv.o: ../../src/video/SDL_yuv.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/SDL_yuv.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_yuv.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsclipboard.o: ../../src/video/windows/SDL_windowsclipboard.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsclipboard.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsclipboard.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsevents.o: ../../src/video/windows/SDL_windowsevents.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsevents.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsevents.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsframebuffer.o: ../../src/video/windows/SDL_windowsframebuffer.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsframebuffer.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsframebuffer.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowskeyboard.o: ../../src/video/windows/SDL_windowskeyboard.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowskeyboard.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowskeyboard.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmessagebox.o: ../../src/video/windows/SDL_windowsmessagebox.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsmessagebox.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmessagebox.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmodes.o: ../../src/video/windows/SDL_windowsmodes.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsmodes.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmodes.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmouse.o: ../../src/video/windows/SDL_windowsmouse.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsmouse.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsmouse.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsopengl.o: ../../src/video/windows/SDL_windowsopengl.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsopengl.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsopengl.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsopengles.o: ../../src/video/windows/SDL_windowsopengles.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsopengles.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsopengles.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsshape.o: ../../src/video/windows/SDL_windowsshape.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsshape.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsshape.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsvideo.o: ../../src/video/windows/SDL_windowsvideo.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsvideo.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsvideo.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowsvulkan.o: ../../src/video/windows/SDL_windowsvulkan.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowsvulkan.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowsvulkan.o

$(APRENDENDO_COM_MEU_MORZAO)SDL_windowswindow.o: ../../src/video/windows/SDL_windowswindow.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/windows/SDL_windowswindow.c" -o $(APRENDENDO_COM_MEU_MORZAO)SDL_windowswindow.o

$(APRENDENDO_COM_MEU_MORZAO)yuv_rgb.o: ../../src/video/yuv2rgb/yuv_rgb.c
	x86_64-w64-mingw32-gcc.exe -c $(AMANDA_FLAGS__) -I "../../include" "../../src/video/yuv2rgb/yuv_rgb.c" -o $(APRENDENDO_COM_MEU_MORZAO)yuv_rgb.o
amanda_smart_ape_clean:
	(cd $(APRENDENDO_COM_MEU_MORZAO) && rm -f *.o)
