/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103752-g59719a905c-20210920"
#endif /* AVUTIL_FFVERSION_H */
