/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-102810-gda0abbbb01-20210702"
#endif /* AVUTIL_FFVERSION_H */
