AMANDA_FLAGS__=-O3 -Wall -Wfatal-errors -Werror
FELINE_FLAGS__=-Wno-unused-function -I. -Wextra  \
-DHAVE_OUR_AMAZING_FUNCTION_strncpy_z
JULIET_FLAGS  =

ALINE_SIZE    =                                  62
	
ricardo_128: 
	@echo 'ok  my master...'
	
	@(cd 'C:/Amanda Ava Pereira/nosso_trabalho/amanda_projects/amandaricardo_koci_rsppmp3_64_bits/rsppmp3 sources/win64/mp3dll/mp3dll/bin/Release/src/c_project/' && make_amanda_kp smartape_v27 && cp --preserve=timestamps  amandaricardo_mvbuild26_33.exe 'C:/AMANDA AVA KOCI PEREIRA/nosso_trabalho/amanda_projects/Seu_Alexandre_cosmopolita_k/rsp_cosmopolita/' )
	
	@./amandaricardo_mvbuild26_33.exe            \
	amanda_s_smart_ape__counter.ini              \
	version_amanda_s_smart_ape.smartape          \
	version_amanda_s_smart_ape.rc                \
	version_amanda_s_smart_ape.hh                \
	"64 bits"                                    \
	Amanda_27.DLL                                \
	increase                                     \
	'2021'                                       \
	'new icon july_i.ico'

	@x86_64-w64-mingw32-gcc -shared              \
	Amanda_27.DEF                                \
	-o Amanda_27.DLL   -O3                       \
	simplemysql.c -lsqlite3 -static              \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)                            \
	INTERFACE2.DLL RSPMP3OCX1.DLL
	
	@x86_64-w64-mingw32-strip Amanda_27.DLL
#	dumppe64 -v ./ape_sample.exe
#	./ape_sample.exe

	@(shopt -s nocaseglob && cp --preserve=timestamps *.ICO *.RC *.smartapE *.C *.H *MAKEFILE* 'C:\Amanda Ava Pereira\nosso_trabalho\amanda_projects\amandaricardo_koci_rsppmp3_64_bits\rsppmp3 sources\win64\mp3dll\mp3dll\bin\Release\src\c_project\sqlite_by_smart_ape')

	@./espaco_arp.exe $(ALINE_SIZE)
	@./espaco_arp.exe $(ALINE_SIZE) 0 51

	@echo 'caralho...do meu amor'

	@cp --preserve=timestamps Amanda_27.DLL 'C:\Amanda Ava Pereira\nosso_trabalho\amanda_projects\amandaricardo_koci_rsppmp3_64_bits\rsppmp3 sources\win64\mp3dll\mp3dll\bin\Release\'

#	dumppe64 -v Amanda_27.DLL
#requires vc6...
mysql:
	cl /Ferspglobalmysql.dll /LD /Ox /MT simplemysql.c mysqlclient.lib WS2_32.LIB ADVAPI32.LIB user32.lib shell32.lib \
	mysql.def

	
